# Generated by Django 4.0.4 on 2022-06-23 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date_added', models.DateField(auto_now=True, verbose_name='Date')),
                ('time_added', models.TimeField(auto_now=True, verbose_name='Time')),
                ('text', models.CharField(max_length=8196)),
                ('pictures', models.ImageField(blank=True, upload_to='article_pics')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('url', models.URLField(max_length=256)),
                ('is_important', models.BooleanField(default=False)),
                ('author', models.ManyToManyField(to='authors.author')),
            ],
        ),
    ]
