# Generated by Django 4.0.4 on 2022-06-23 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(choices=[('1', 'Sports'), ('2', 'People'), ('3', 'Auto'), ('4', 'Culture'), ('5', 'Politics'), ('6', 'Society'), ('7', 'Business'), ('8', 'Economy')], null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
