# Generated by Django 4.0.4 on 2022-06-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_category',
        ),
    ]
