# Generated by Django 4.0.4 on 2022-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_tags_alter_article_text_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True, unique=True),
        ),
    ]
