# Generated by Django 4.0.4 on 2022-06-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_important',
        ),
        migrations.AlterField(
            model_name='article',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, null=True),
        ),
    ]
