# Generated by Django 4.0.4 on 2022-06-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_priority_article_no_important_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='priority',
            new_name='no_important',
        ),
    ]
