# Generated by Django 4.0.4 on 2022-06-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_priority_article_no_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_by',
        ),
    ]
