# Generated by Django 4.0.4 on 2022-07-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_article_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='no_homepage',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
