# Generated by Django 4.0.4 on 2022-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_article'),
        ('articles', '0013_alter_article_no_homepage_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
