# Generated by Django 4.0.4 on 2022-07-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
    ]
