# Generated by Django 4.0.4 on 2022-07-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_article_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pictures',
            new_name='article_pic',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='video',
            new_name='article_video',
        ),
    ]
