# Generated by Django 4.0.4 on 2022-07-29 08:52

import articles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_rename_pictures_article_article_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(blank=True, upload_to=articles.models.get_img_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_video',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.get_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
