# Generated by Django 4.0.4 on 2022-08-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
