# Generated by Django 4.0.4 on 2022-08-12 08:49

import VerginaNews.utils
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[665, 404], upload_to=VerginaNews.utils.get_img_path, validators=[VerginaNews.utils.image_size_validator]),
        ),
    ]
