# Generated by Django 4.0.4 on 2022-08-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_video',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
