# Generated by Django 4.0.4 on 2023-05-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_name'),
        ('articles', '0033_alter_article_article_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
        ),
    ]
