# Generated by Django 4.0.4 on 2023-05-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_alter_author_prof_pic'),
        ('articles', '0034_alter_article_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, to='authors.author'),
        ),
    ]
