# Generated by Django 4.0.4 on 2023-05-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
