# Generated by Django 4.0.4 on 2023-05-28 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_remove_article_time_added_alter_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 19, 5, 59, 326247), verbose_name='Date'),
        ),
    ]
