# Generated by Django 4.0.4 on 2023-05-28 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0038_alter_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 20, 19, 41, 675906), verbose_name='Date'),
        ),
    ]
