# Generated by Django 4.0.4 on 2023-05-29 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0039_alter_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 12, 28, 10, 901092), verbose_name='Date'),
        ),
    ]
