# Generated by Django 4.0.4 on 2023-05-29 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0040_alter_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 0, 33, 18, 382416), verbose_name='Date'),
        ),
    ]
