# Generated by Django 4.0.4 on 2022-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('prof_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('email', models.EmailField(max_length=254)),
                ('short_bio', models.CharField(max_length=512)),
                ('job_title', models.CharField(choices=[('1', 'Sports'), ('2', 'People'), ('3', 'Auto'), ('4', 'Culture'), ('5', 'Politics'), ('6', 'Society'), ('7', 'Business'), ('8', 'Economy')], max_length=1)),
            ],
        ),
    ]
