# Generated by Django 4.0.4 on 2022-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='featured',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
