# Generated by Django 4.0.4 on 2022-07-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='author_pics'),
        ),
    ]
