# Generated by Django 4.0.4 on 2022-07-28 20:07

import authors.models
from django.db import migrations, models
from VerginaNews.utils import get_img_path


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to=get_img_path),
        ),
    ]
