# Generated by Django 4.0.4 on 2022-07-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_author_prof_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='featured',
        ),
    ]
