# Generated by Django 4.0.4 on 2022-08-20 08:27

import VerginaNews.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_author_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to=VerginaNews.utils.get_img_path),
        ),
    ]
