# Generated by Django 4.0.4 on 2022-08-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_remove_author_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='job_title',
            field=models.CharField(choices=[('1', 'Sports'), ('2', 'People'), ('3', 'Auto'), ('4', 'Culture'), ('5', 'Politics'), ('6', 'Society'), ('7', 'Business'), ('8', 'Economy')], max_length=10, null=True),
        ),
    ]
