# Generated by Django 4.0.4 on 2022-08-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_name'),
        ('authors', '0011_author_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
