# Generated by Django 4.0.4 on 2022-08-23 10:12

import VerginaNews.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_author_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to=VerginaNews.utils.get_img_path, validators=[VerginaNews.utils.image_size_validator]),
        ),
    ]
