# Generated by Django 4.0.4 on 2022-08-30 08:28

import VerginaNews.utils
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0013_alter_author_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='prof_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=60, scale=None, size=[400, 400], upload_to=VerginaNews.utils.get_img_path, validators=[VerginaNews.utils.image_size_validator]),
        ),
    ]
