# Generated by Django 4.0.4 on 2023-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0017_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='job_title',
        ),
    ]
