# Generated by Django 4.0.4 on 2022-07-30 08:41

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_pic',
            field=models.ImageField(upload_to=ads.models.get_file_path),
        ),
    ]
