# Generated by Django 4.0.4 on 2022-08-01 13:06

import ads.models
from django.db import migrations, models
from VerginaNews.utils import get_img_path


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_priority_alter_ad_ad_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_pic',
            field=models.ImageField(blank=True, upload_to=get_img_path),
        ),
    ]
