# Generated by Django 4.0.4 on 2022-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_googlead_alter_ad_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlead',
            name='widget',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
