# Generated by Django 4.0.4 on 2022-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_googlead_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Homepage Banner 1'), ('2', 'Home VerginaNews 1'), ('3', 'Home VerginaNews 2'), ('4', 'Home VerginaNews 3'), ('5', 'Home VerginaNews 4'), ('6', 'Homepage Banner 2'), ('7', 'Article Banner'), ('8', 'Article Sidebar'), ('9', 'Author Sidebar'), ('10', 'Category/SubCategory Sidebar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='googlead',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Homepage Banner 1'), ('2', 'Home VerginaNews 1'), ('3', 'Home VerginaNews 2'), ('4', 'Home VerginaNews 3'), ('5', 'Home VerginaNews 4'), ('6', 'Homepage Banner 2'), ('7', 'Article Banner'), ('8', 'Article Sidebar'), ('9', 'Author Sidebar'), ('10', 'Category/SubCategory Sidebar')], max_length=10, null=True),
        ),
    ]
