# Generated by Django 4.0.4 on 2022-08-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_subcategory_options_alter_category_slug_and_more'),
        ('tags', '0003_tags_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
        ),
    ]
