# Generated by Django 4.0.4 on 2022-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_remove_tags_category_tags_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
