# Generated by Django 4.0.4 on 2022-08-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_subcategory_options_alter_category_slug_and_more'),
        ('tags', '0007_alter_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='category',
        ),
        migrations.AddField(
            model_name='tags',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='tags',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='tags',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
        ),
    ]
