# Generated by Django 4.0.4 on 2022-08-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_subcategory_options_alter_category_slug_and_more'),
        ('tags', '0009_remove_tags_category_tags_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='sub_category',
            field=models.ManyToManyField(to='categories.subcategory'),
        ),
    ]
