# Generated by Django 4.0.4 on 2022-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_alter_tags_category_alter_tags_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
