# Generated by Django 4.0.4 on 2023-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_alter_tags_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(to='tags.tags')),
            ],
        ),
    ]
