# Generated by Django 4.0.4 on 2023-05-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_tagcloud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcloud',
            options={'verbose_name_plural': 'Tag Cloud'},
        ),
        migrations.RemoveField(
            model_name='tagcloud',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagcloud',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tags'),
        ),
    ]
