# Generated by Django 4.0.4 on 2023-05-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_name'),
        ('tags', '0014_remove_tagcloud_tags_tagcloud_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='categories.subcategory'),
        ),
    ]
