# Generated by Django 4.0.4 on 2023-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.TextField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitch', 'Twitch'), ('Twitter', 'Twitter'), ('Linkedin', 'Linkedin'), ('Youtube', 'Youtube')], unique=True),
        ),
    ]
